---
name: Build and test

"on":
  push:
    branches: ["**"]

env:
  swift-version: '5.9'

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        configuration: [Debug, Release]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: false

      - uses: compnerd/gha-setup-vsdevenv@main

      - name: Set up swift (Windows)
        uses: compnerd/gha-setup-swift@v0.2.1
        with:
          branch: swift-${{ env.swift-version }}-release
          tag: ${{ env.swift-version }}-RELEASE

      - name: Swift Package Manager
        run: swift test
